[[modules.beginning]]
type = "cinnabar.modules.dummy"
id = "left-dummy"

[[modules.middle]]
type = "cinnabar.modules.clock"
id = "clock"
format = "{:%Y-%m-%d %H:%M:%S}"

[[modules.end]]
type = "cinnabar.modules.dummy"
id = "right-dummy"

# Can use "array of objects" syntax!
[[modules.end]]
type = "cinnabar.modules.dummy"
id = "right-dummy2"
