[[widgets.beginning]]
type = "cinnabar.plugins.dummy"

[[widgets.middle]]
type = "cinnabar.plugins.clock"
format = "{:%Y-%m-%d %H:%M:%S}"

[[widgets.end]]
type = "cinnabar.plugins.dummy"

[[widgets.end]]
type = "cinnabar.plugins.dummy"
